interface HeatMapInterface {
    "dayOfWeek": string|number|null,
    "00h": string|number|null,
    "01h": string|number|null,
    "02h": string|number|null,
    "03h": string|number|null,
    "04h": string|number|null,
    "05h": string|number|null,
    "06h": string|number|null,
    "07h": string|number|null,
    "08h": string|number|null,
    "09h": string|number|null,
    "10h": string|number|null,
    "11h": string|number|null,
    "12h": string|number|null,
    "13h": string|number|null,
    "14h": string|number|null,
    "15h": string|number|null,
    "16h": string|number|null,
    "17h": string|number|null,
    "18h": string|number|null,
    "19h": string|number|null,
    "20h": string|number|null,
    "21h": string|number|null,
    "22h": string|number|null,
    "23h": string|number|null,
}

export default HeatMapInterface;